apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ilst-ingress
  namespace: ibm-licensing
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" # <- HTTPS or HTTP depanding of the setting of httpsEnable in the IBMLicensing instance
spec:
  ingressClassName: nginx
  rules:
    - host: {{.Values.host.name}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ibm-licensing-service-instance
                port:
                  number: 8080
